// Code generated by 'ccgo limits/gen.c -ccgo-crt-import-path  -ccgo-export-defines  -ccgo-export-enums  -ccgo-export-externs X -ccgo-export-fields F -ccgo-export-structs  -ccgo-export-typedefs  -ccgo-host-config-cmd  -ccgo-host-config-opts  -ccgo-pkgname limits -o limits/limits_linux_386.go', DO NOT EDIT.

package limits

var CAPI = map[string]struct{}{}
