// Code generated by 'ccgo pwd/gen.c -D__signed__=signed -D__attribute__(x)= -ccgo-crt-import-path  -ccgo-export-defines  -ccgo-export-enums  -ccgo-export-externs X -ccgo-export-fields F -ccgo-export-structs  -ccgo-export-typedefs  -ccgo-header -ccgo-long-double-is-double -ccgo-pkgname pwd -o pwd/pwd_linux_386.go', DO NOT EDIT.

package pwd

var CAPI = map[string]struct{}{}
