// Code generated by 'ccgo signal/gen.c -ccgo-crt-import-path  -ccgo-export-defines  -ccgo-export-enums  -ccgo-export-externs X -ccgo-export-fields F -ccgo-export-structs  -ccgo-export-typedefs  -ccgo-hide _OSSwapInt16,_OSSwapInt32,_OSSwapInt64 -ccgo-hide-asm -ccgo-long-double-is-double -ccgo-pkgname signal -o signal/signal_linux_amd64.go', DO NOT EDIT.

package signal

var CAPI = map[string]struct{}{}
