// Code generated by 'ccgo sys/types/gen.c -ccgo-crt-import-path  -ccgo-export-defines  -ccgo-export-enums  -ccgo-export-externs X -ccgo-export-fields F -ccgo-export-structs  -ccgo-export-typedefs  -ccgo-host-config-cmd  -ccgo-host-config-opts  -ccgo-pkgname types -o sys/types/types_linux_386.go', DO NOT EDIT.

package types

var CAPI = map[string]struct{}{}
