// Code generated by 'ccgo /tmp/go-generate-230143997/x.c -ccgo-crt-import-path  -ccgo-export-defines  -ccgo-export-enums  -ccgo-export-externs X -ccgo-export-fields F -ccgo-export-structs  -ccgo-export-typedefs  -ccgo-pkgname types -o sys/types/types_linux_amd64.go', DO NOT EDIT.

package types

var CAPI = map[string]struct{}{}
