// Code generated by 'ccgo fts/gen.c -D__signed__=signed -D__attribute__(x)= -ccgo-crt-import-path  -ccgo-export-defines  -ccgo-export-enums  -ccgo-export-externs X -ccgo-export-fields F -ccgo-export-structs  -ccgo-export-typedefs  -ccgo-header -ccgo-long-double-is-double -ccgo-pkgname fts -o fts/fts_linux_amd64.go', DO NOT EDIT.

package fts

var CAPI = map[string]struct{}{}
