// Code generated by 'ccgo fcntl/gen.c -D__signed__=signed -ccgo-crt-import-path  -ccgo-export-defines  -ccgo-export-enums  -ccgo-export-externs X -ccgo-export-fields F -ccgo-export-structs  -ccgo-export-typedefs  -ccgo-long-double-is-double -ccgo-pkgname fcntl -o fcntl/fcntl_darwin_amd64.go -ccgo-hide-asm', DO NOT EDIT.

package fcntl

var CAPI = map[string]struct{}{}
