// Code generated by 'ccgo sys/socket/gen.c -D__signed__=signed -D__attribute__(x)= -ccgo-crt-import-path  -ccgo-export-defines  -ccgo-export-enums  -ccgo-export-externs X -ccgo-export-fields F -ccgo-export-structs  -ccgo-export-typedefs  -ccgo-header -ccgo-long-double-is-double -ccgo-pkgname socket -o sys/socket/socket_linux_amd64.go', DO NOT EDIT.

package socket

var CAPI = map[string]struct{}{}
