// Code generated by 'ccgo sys/socket/gen.c -ccgo-crt-import-path  -ccgo-export-defines  -ccgo-export-enums  -ccgo-export-externs X -ccgo-export-fields F -ccgo-export-structs  -ccgo-export-typedefs  -ccgo-hide _OSSwapInt16,_OSSwapInt32,_OSSwapInt64 -ccgo-hide-asm -ccgo-long-double-is-double -ccgo-pkgname socket -o sys/socket/socket_darwin_amd64.go', DO NOT EDIT.

package socket

var CAPI = map[string]struct{}{}
