// Code generated by 'ccgo sys/socket/gen.c -ccgo-crt-import-path  -ccgo-export-defines  -ccgo-export-enums  -ccgo-export-externs X -ccgo-export-fields F -ccgo-export-structs  -ccgo-export-typedefs  -ccgo-host-config-cmd  -ccgo-host-config-opts  -ccgo-pkgname socket -o sys/socket/socket_linux_386.go', DO NOT EDIT.

package socket

var CAPI = map[string]struct{}{}
