// Code generated by 'ccgo /tmp/go-generate-721359862/x.c -ccgo-crt-import-path  -ccgo-export-defines  -ccgo-export-enums  -ccgo-export-externs X -ccgo-export-fields F -ccgo-export-structs  -ccgo-export-typedefs  -ccgo-pkgname socket -o sys/socket/socket_linux_amd64.go', DO NOT EDIT.

package socket

var CAPI = map[string]struct{}{}
