// Code generated by 'ccgo unistd/gen.c -ccgo-crt-import-path  -ccgo-export-defines  -ccgo-export-enums  -ccgo-export-externs X -ccgo-export-fields F -ccgo-export-structs  -ccgo-export-typedefs  -ccgo-host-config-cmd  -ccgo-host-config-opts  -ccgo-pkgname unistd -o unistd/unistd_linux_386.go', DO NOT EDIT.

package unistd

var CAPI = map[string]struct{}{}
