// Code generated by 'ccgo unistd/gen.c -ccgo-crt-import-path  -ccgo-export-defines  -ccgo-export-enums  -ccgo-export-externs X -ccgo-export-fields F -ccgo-export-structs  -ccgo-export-typedefs  -ccgo-hide _OSSwapInt16,_OSSwapInt32,_OSSwapInt64 -ccgo-hide-asm -ccgo-long-double-is-double -ccgo-pkgname unistd -o unistd/unistd_darwin_amd64.go', DO NOT EDIT.

package unistd

var CAPI = map[string]struct{}{}
