// Code generated by 'ccgo termios/gen.c -D__signed__=signed -D__attribute__(x)= -ccgo-crt-import-path  -ccgo-export-defines  -ccgo-export-enums  -ccgo-export-externs X -ccgo-export-fields F -ccgo-export-structs  -ccgo-export-typedefs  -ccgo-header -ccgo-long-double-is-double -ccgo-pkgname termios -o termios/termios_linux_386.go', DO NOT EDIT.

package termios

var CAPI = map[string]struct{}{}
