// Code generated by 'ccgo termios/gen.c -ccgo-crt-import-path  -ccgo-export-defines  -ccgo-export-enums  -ccgo-export-externs X -ccgo-export-fields F -ccgo-export-structs  -ccgo-export-typedefs  -ccgo-pkgname termios -o termios/termios_linux_amd64.go', DO NOT EDIT.

package termios

var CAPI = map[string]struct{}{}
