// Code generated by 'ccgo /tmp/go-generate-104800690/x.c -ccgo-crt-import-path  -ccgo-export-defines  -ccgo-export-enums  -ccgo-export-externs X -ccgo-export-fields F -ccgo-export-structs  -ccgo-export-typedefs  -ccgo-pkgname errno -o errno/errno_linux_amd64.go', DO NOT EDIT.

package errno

var CAPI = map[string]struct{}{}
